### ISSUE TITLE
2.0 Shaman Feedback Thread

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-Heroes-Handbook#98]
## Shaman Feedback

Putting this one up here as a general pooling point for shaman feedback, with the 2.0 release of the handbook.

### General

- Comment on a general lack of a central ranged utility, especially when playing as an enhancement shaman?

  - With the Ghost From, a shaman is able to cover considerable amount of ground in a short timespan, making it relatively easy for them to engage in melee with their opponents.

  - At lower levels, it's also an option for a shaman to simply bring a ranged weapon along. At higher levels, spell slots can be used for ranged spells. 

  - The enhancement shaman is pretty melee centric, by design.

- Not having a ranged spell filler feels odd for Elemental and Restoration, outside of using levelled spells. 

- Comment on Imbue Weapons, making it feel like a loss, having to use 2 spell slots to imbue both weapons when you can only make 1 attack with your off-hand, leaning Enhancement more towards 2-handed combat.

- Comment on whether Elemental and Restoration manage to fit into the half caster niche.

- Does it work to work Imbue Weapon together with dual-wielding? Does it work to have it engaged as a bonus action (versus, say, expending a spell slot on hit as a smite would)?

- Only Enhancement seems to benefit greatly from having fighting styles. Elemental particularly would not have use for weapon-oriented bonuses. 

### Class Errors

- Elemental Shield: Water needs to specify that you can only reroll damage and healing dice. Not spell attacks.

### Totems

- Comment on a lack of healing-oriented totems. Given the cantrip-like nature of the totems, and the fact that healing cantrips deliberately do not exist, there probably shouldn't be any healing totems.

  - If we were to cover a niche like this, we'd likely need to consider tying some kind of resource mechanic back to them.

**Comment by Jihia** [comment]
Added Class Error section for comments about specific class features which are lacking clarification or straight up wrong.
