### ISSUE TITLE
2.0 Warrior Feedback Thread

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-Heroes-Handbook#99]
## Warrior Feedback

Putting this one up here as a general pooling point for warrior feedback, with the 2.0 release of the handbook.

### General

- Some talk about whether getting rage points all at once and then spending it, meets the expected fantasy of gaining it gradually by fighting. 

  - Mention of Matthew Mercers' rage mechanic from his WoW [Oneshot.](https://www.dropbox.com/sh/27p491g3zoocmu9/AADVfJJenoBwW6EK4bfFk7f-a?dl=0&preview=Mag%27har+Orc+Warrior.pdf) 

  - [Power Surge](http://dnd5e.wikidot.com/wizard:war-magic) mentioned.

- "If you pop your only rage for the day and don't use all your rage points, it'd be a pretty bad feeling."

- Some talk about the rage features, and missing something more defensive.
   - Potentially add in a rage option to be used as a reaction upon taking damage, to gain resistance towards bludgeoning, piercing, and slashing from nonmagical attacks.

**Comment by orjanbp** [comment]
Additional comments added. Mentions of War Wizards' Power Surge, and the feeling of needing to manage rage economy to not waste the resource.

**Comment by Jihia** [comment]
Additional comments added. Mention of defensive rage ability
